name: ledge
description: "A sophisticated Flutter expense tracking application with minimalist design and data visualizations."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Data visualization
  fl_chart: ^0.68.0

  # Local storage
  shared_preferences: ^2.3.2

  # Date formatting
  intl: ^0.19.0

  # State management
  provider: ^6.1.2

  # Unique IDs
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Launcher icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
